name: CI
on:
  push:
      branches: [chosoianchao]
  pull_request:
      branches: [chosoianchao]
  workflow_dispatch:
jobs:
    build:
          runs-on: ubuntu-latest
          steps:
                - uses: actions/news@master
                - name: Run a one-line script
                  run: echo Hello, world!
                - name: Run a multi-line-script
                  run: echo Add orther actions to build,
                        echo test, and deploy project.
